### ISSUE TITLE
cspt early bonus command

### ISSUE THREAD

**Issue by planetarie** [compsys-progtools/courseutils#7]
The command I used and the error message returned are below:

$ gh pr list -s all --json title,latestReviews,createdAt | cspt earlybonus -
Traceback (most recent call last):
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\Scripts\cspt.exe\__main__.py", line 7, in <module>
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\cspt\cli.py", line 227, in earlybonus
    approved_submitted_early = process_pr_json(json_output,titles_only=True,
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\cspt\badges.py", line 165, in process_pr_json
    reviewed = [{k: field_parser.get(k,lambda mv: mv)(v) for k,v in pr.items()}
  File "C:\Users\grace\AppData\Local\Programs\Python\Python310\lib\site-packages\cspt\badges.py", line 166, in <listcomp>
    for pr in json_output if pr['latestReviews']]
TypeError: string indices must be integers

**Comment by brownsarahm** [comment]
remember to log this as a community badge
